name: Create Release

on:
  push:
    branches:
      - dev
      - stable

jobs:
  builds:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          platformio update
      - name: Checkout
        uses: actions/checkout@v2
      # TODO build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false